version: "3.9"

services:
  english-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD:-YourStrong!Passw0rd}"
    ports:
      - "1433:1433"
    volumes:
      - english-data:/var/opt/mssql
    networks:
      - english-net
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD:-YourStrong!Passw0rd}" -Q "SELECT 1" -C -b
      interval: 10s
      timeout: 5s
      retries: 10

  english-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    depends_on:
      english-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "mssql+aioodbc://sa:${SA_PASSWORD:-YourStrong!Passw0rd}@english-db:1433/EnglishDB?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes&LongAsMax=Yes"
      DATABASE_MIGRATION_URL: "mssql+pyodbc://sa:${SA_PASSWORD:-YourStrong!Passw0rd}@english-db:1433/EnglishDB?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes&LongAsMax=Yes"
    networks:
      - english-net

volumes:
  english-data:

networks:
  english-net:
