from dataclasses import dataclass
from uuid import UUID
import datetime


@dataclass
class ExercisePrompt:
    """Generated by the LLM: the scenario and sentences the user sees before answering."""
    practice_term_id: UUID | None
    practice_term_text: str
    term_type: str
    target_language_code: str
    scenario_native: str
    sentence_native: str
    sentence_target: str


@dataclass
class ExerciseEvaluation:
    """Returned by the LLM after evaluating the user's answer."""
    is_correct: bool
    feedback: str
    correct_example: str | None = None


@dataclass
class ExerciseHistoryRecord:
    """Persisted record of a completed exercise attempt."""
    id: UUID | None
    user_id: UUID
    practice_term_id: UUID
    exercise_type: str
    target_language_code: str
    scenario_native: str
    sentence_native: str
    sentence_target: str
    user_answer: str
    is_correct: bool
    feedback: str
    created_at: datetime.datetime | None = None


@dataclass
class PracticeTermStats:
    """Aggregated stats for a single practice term for a user."""
    practice_term_id: UUID
    term: str
    term_type: str
    correct_count: int
    incorrect_count: int
