from dataclasses import dataclass, field
from uuid import UUID
import datetime


@dataclass
class MultiplePrepositionsExercisePrompt:
    """Generated by the LLM: a native sentence whose translation must use
    several specific prepositions, plus the LLM's reference English translation
    (kept server-side; never returned to the client during generation)."""
    practice_term_ids: list[UUID]
    practice_term_texts: list[str]
    target_language_code: str
    sentence_native: str
    sentence_target: str


@dataclass
class MultiplePrepositionsEvaluation:
    """Returned by the LLM after evaluating the user's translation."""
    is_correct: bool
    feedback: str
    preposition_feedback: list[dict] = field(default_factory=list)
    minor_issues: list[str] = field(default_factory=list)
    correct_sentence_target: str | None = None


@dataclass
class MultiplePrepositionsExerciseHistoryRecord:
    """Persisted record of a completed multiple-prepositions attempt."""
    id: UUID | None
    user_id: UUID
    practice_term_ids: list[UUID]
    target_language_code: str
    sentence_native: str
    sentence_target: str
    user_answer: str
    attempt_number: int
    is_correct: bool
    feedback: str
    revealed: bool
    created_at: datetime.datetime | None = None
